version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment: 
      - MONGO_URI=${MONGO_URI}
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      -mongodb


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "3000:80"

    depends_on:
      -backend

  mongodb:
    image: mongo
    ports: 
      - "27017:27017"

    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoUser
      - MONGO_INITDB_ROOT_USERNAME=mongoPassword
    